import React from "react";
import Head from "next/head";

const Subscribe = () => {
  return (
    <>
      <Head>
        <title>Sayan Munshi - Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font relative">
        <div className="container px-5 pb-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-12">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Subscribe
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
              Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical
              gentrify.
            </p>
          </div>
          <div className="lg:w-1/2 md:w-2/3 mx-auto">
            <div className="flex flex-wrap -m-2">
              <div className="p-2 w-full">
                <div className="relative">
                  <label
                    htmlFor="email"
                    className="leading-7 text-sm text-gray-600"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                  />
                </div>
              </div>
              <div className="p-2 w-full">
                <button className="btn btn-primary flex mx-auto text-white border-0 py-2 px-8 focus:outline-none hover:btn-secondary rounded text-lg">
                  Subscribe
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export async function getServerSideProps(context) {
  const headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  let categories;

  const categoryArrRes = await fetch(
    `${process.env.API_URL}api/categories?populate=*`,
    {
      headers: headers,
    }
  );

  const categoryArr = await categoryArrRes.json();

  categories = categoryArr.data;

  return {
    props: { categories }, // will be passed to the page component as props
  };
}

export default Subscribe;
